/**
 * generateAutomation — transactional operation on a test case.
 *
 * Takes a testCaseId (currently the id of an `AiCase` — the AI-generated
 * case from the chat review flow), generates a Playwright automation
 * template, and emits `case.confirmed` on the bus.
 *
 * In the future this aggregate may use the dedicated `TestCase` entity
 * (Suite.cases[]) — for the demo we operate on `AiCase` because that's
 * the data shape the chat-review flow already produces and the user can
 * click "Generate automation" on without manual setup. The function
 * signature is generic over `testCaseId: string` so the swap is local.
 *
 * The "code generation" for the demo is a deterministic template —
 * real AI generation is a future concern (REQ-PROJ-007 + REQ-PROJ-008).
 * The shape returned is what a UI "View generated code" panel would render.
 */
import { getAiCase } from '@/lib/mock-store'
import { eventBus } from '@/lib/event-bus'

const PLAYWRIGHT_TEMPLATE = (caseName: string) => `import { test, expect } from '@playwright/test'

test('${caseName.replace(/'/g, "\\'")}', async ({ page }) => {
  // Generated by Qably
  await page.goto('/')
  // TODO: implement steps from the test case description
  await expect(page.locator('main')).toBeVisible()
})
`

export interface GeneratedAutomation {
  caseId: string
  projectId: string
  code: string
  generatedAt: string
}

export function generateAutomation(testCaseId: string): GeneratedAutomation | undefined {
  const testCase = getAiCase(testCaseId)
  if (!testCase) return undefined

  const code = PLAYWRIGHT_TEMPLATE(testCase.name)

  eventBus.emit('case.confirmed', {
    projectId: testCase.projectId,
    caseId: testCase.id,
  })

  return {
    caseId: testCase.id,
    projectId: testCase.projectId,
    code,
    generatedAt: new Date().toISOString(),
  }
}
